### ISSUE TITLE
multiple input file and output file

### ISSUE THREAD

**Issue by ilhamdev0** [waynevanson/rollup-stream-gulp#2]
If I have multiple javascript file in my project lets say

```
src/

a.js
b.js
```

and then in gulpfile.js

```
gulp.src("src/*.js").pipe(rollup({})).pipe(gulp.dest("dist"));
```

so it got multiple file input instead of a single file. is it possible with this plugin to have multiple output like this?

```
dist/

a.min.js
b.min.js
```

**Comment by waynevanson** [comment]
Have you tried it?

You need to add an output, like in the example.

If it doesn't work, this might be the issue.

https://github.com/waynevanson/rollup-stream-gulp/blob/3f2390a388fd36584c6977259842a72c61df8d87/src/index.ts#L36-L37

**Comment by ilhamdev0** [comment]
I was tested this and it's worked by adding `output` inside rollup config. Thanks for suggestion

closing this now
